simp/pupmod-simp-rsyslog

- build/pupmod-rsyslog.spec
- spec/classes/global_spec.rb
- templates/rsyslog.conf.global.erb
This updates the system to ensure that the global template does not fail
if actionSendStreamDriverPermittedPeers is an empty array.
SIMP-321 #close #comment Fix for actionSendStreamDriverPermittedPeers being an empty array
> (SIMP-321) Allow empty log_servers Hiera parameter

- spec/acceptance/nodesets/centos-66-x64.yml
- spec/acceptance/nodesets/centos-7-x64.yml
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/fedora-20-x64.yml
Before this commit, a 4-host acceptance test run took 4GB RAM to run.
This update reduces the RAM requirement per VM from 1GB to 384MB.
SIMP-192 #comment Reduced per-VM RAM footprint for acceptance tests
> (SIMP-192) Reduce memory usage of acceptance tests

- Gemfile
- spec/acceptance/client_server_using_tls_spec.rb
- spec/acceptance/failover_using_tls_spec.rb
The SIMP beaker Gem was updated to better mirror the action of
::pki::copy. This adjusts the acceptance tests accordingly.
SIMP-192 #comment PKI Acceptance Test Update
Change-Id: Ibbc56dac24e5a4a3a4476cc8f4dabe02621f57a9
> (SIMP-192) Update acceptance tests for PKI update

- Gemfile
- manifests/install.pp
- spec/spec_helper_acceptance.rb
Before this commit, it was impossible to use this module to install
`rsyslog7` on an EL6 system using the stock `rsyslog` (v5) without
force-uninstalling rsyslog while ignoring dependencies.
This commit ensures that `rsyslog` is uninstalled without dependencies
before installing `rsyslog7`.
NOTE: If the package exchange occurs on an actively logging system,
logging will be very briefly interrupted during the interregnum.
SIMP-567 #close #comment Remove rsyslog before installing rsyslog7.
> (SIMP-567) Remove rsyslog before rsyslog7 install

- .fixtures.yml
- build/pupmod-rsyslog.spec
Before this commit, common SIMP-related custom functions were been kept
in either `simp-common` or `simp-functions`, and the `concat` function
was provided by the `simp-concat` module.  These functions are now
provides by the `simp-simplib` and `simp-simpcat` modules, respectively.
This update replaces all requirements in the RPM spec file,
metadata.json, or .fixtures.yml to reflect the migration to the new
modules.
SIMP-601 #comment Migrated `pupmod-simp-rsyslog`.
SIMP-604 #comment Updated `pupmod-simp-rsyslog`.
> (SIMP-604) Migrate to simplib and simpcat

- .gitignore
- .puppet-lint.rc
- .travis.yml
- CONTRIBUTING.md
- Gemfile
- Rakefile
- manifests/config.pp
- manifests/config/pki.pp
- manifests/install.pp
- manifests/params.pp
- manifests/server/selinux.pp
This commit synchronizes all common static module assets with current SIMP
module standards.
Also:
- created .puppet-lint.rc, .travis.yml, .gitignore
SIMP-667 #comment updated `pupmod-simp-rsyslog`
SIMP-741 #close #comment normalized common module assets
> (SIMP-667) Normalize common module assets

- .travis.yml
- Gemfile
- Rakefile
- spec/spec_helper.rb
Before this patch, this module would fail its spec tests when
`STRICT_VARIABLES=yes` is set (as it is in Travis CI tests).
This was caused by the presence of the unset (and unused) variable
"spec_title" in the modules' fixture hieradata/hiera.yaml.
This commit fixes the issue by removing "spec_title" from
each module's hieradata/hiera.yaml.
SIMP-1054 #comment Fixed pupmod-simp-rsyslog
SIMP-1093 #close Fixed spec failures when `STRICT_VARIABLES=yes`
> (SIMP-1054) Update static assets to fix spec tests

- .fixtures.yml
- .gitignore
- .travis.yml
- Gemfile.lock
- manifests/config.pp
- manifests/init.pp
- manifests/server/firewall.pp
- metadata.json
- spec/acceptance/suites/default/01_client_server_no_tls_spec.rb
- spec/acceptance/suites/default/02_client_server_udp_spec.rb
- spec/acceptance/suites/default/03_client_server_using_tls_spec.rb
- spec/acceptance/suites/default/04_failover_no_tls_spec.rb
- spec/acceptance/suites/default/05_failover_using_tls_spec.rb
- spec/classes/server_spec.rb
Before this patch:
* `rsyslog::server::firewall` still used the API for
pupmod-simp-iptables 5.x, which would fail during acceptance tests.
*  Spec tests for `rsyslog::server::firewall` checked that the toggle
had worked, but didn't configure any of the `rsyslog` parameters that
would actually configure the firewall.
* The versions loaded by .fixtures.yml and specified by metadata.json
disagreed, resutling in a lot of warning chatter during acceptance
tests.
This commit solves those issues by updating the iptables code to 6.x,
adding more robust tests for the `rsyslog::server::firewall` logic, and
updating the iptables syntax during the rsyslog beaker:suites.
SIMP-2439 #close
SIMP-2394 #close #comment locked dependencies
SIMP-1158 #comment fix minor strings errors in pupmod-simp-rsyslog
> (SIMP-2439) Fix and test `iptables::listen::`

- CHANGELOG
- manifests/config/logrotate.pp
- updated expression to execute correctly.
SIMP-2663 #close
> (SIMP-2663) Lastaction not being set properly for syslog rotate.

- spec/defines/rule/remote_spec.rb
- templates/rule/remote.erb
- "Calls" in rsyslog remote rules don't work when the first
character is a number.
- Changed the call name to start with the word "ruleset".
- File names still start with the order to keep priority.
SIMP-2693 #close
> (SIMP-2693) Fix rsyslog remote ruleset call name

- CHANGELOG
- manifests/server.pp
- metadata.json
- spec/classes/server_spec.rb
rsyslog::server used to use simp_options::selinux to determine if
selinux should be modified. Now it uses the current state of the system.
SIMP-2948 #close
> (SIMP-2948) Use selinux status instead of catalyst

- CHANGELOG
- files/config/rsyslog.default
- spec/acceptance/suites/default/00_default_spec.rb
- Fixed bug in which default iptables rsyslog rule did not work
with rsyslog version 7.4.7.  Some versions of rsyslog include
the ' ' separator in the message payload, which impacts the
startswith rule.
- Fixed bug whereby puppetserver log messages were not being
collected in puppetserver-specific logs.
> (SIMP-3268) Problem default rsyslog rules

- .travis.yml
Revert bundler version pinning, now that 4.0.1 simp-rake-helpers no
longer requires it. This version pinning was causing gitlab-ci
problems.
SIMP-3476 #close
> (SIMP-3476) rsyslog: Revert bundler version pinning

- CHANGELOG
- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- manifests/rule/remote.pp
- spec/acceptance/nodesets/centos-6.yml
- spec/acceptance/suites/default/00_default_spec.rb
- spec/acceptance/suites/doubleforward/01_client_tls_server_no_tls_nextserver_spec.rb
- spec/acceptance/suites/doubleforward/nodesets/centos-6.yml
- spec/acceptance/suites/doubleforward/nodesets/default.yml
- spec/acceptance/suites/doubleforward/nodesets/oel.yml
- spec/classes/init_spec.rb
- templates/config/pre_logging.conf.erb
- templates/rule/remote.erb
pupmod-simp-rsyslog does not allow a TSL encrypted server to
be configured to forward to a follow-on, unencrypted rsyslog server.
This PR incorporates the initial Rsyslog 8 solution provided by Ralph Wright.
- Removed all ActionSendStreamDriver* directives from the global
configuration for Rsyslog 8.
- Only set ActionSendStreamDriverMode in global configuration
for Rsyslog 7 when sending TLS-encrypted messages.
- Updated manifest documentation for clarity
- Fixed bug in default suite acceptance test that did not allow
centos-6.yml node set to be run.
- Added a double forward acceptance test:
client -> TLS server -> plain TCP server
SIMP-5137 #close
SIMP-5138 #close
> (SIMP-967) Cannot config TLS rsyslog server to unencrypted one

- CHANGELOG
- metadata.json
- spec/acceptance/suites/default/00_default_spec.rb
These were innocuous but could cause confusion as we move away from
using sudosh.
> (SIMP-5099) Remove sudosh references from tests

- CHANGELOG
- manifests/init.pp
- Updated $app_pki_external_source to accept any string. This matches the
functionality of pki::copy.
SIMP-5296 #comment Updated simp-rsyslog
SIMP-5298 #close
> (SIMP-5298) updated $app_pki_external_source type

- .fixtures.yml
- .gitlab-ci.yml
- .travis.yml
- CHANGELOG
- metadata.json
- Update to camptocamp/systemd 2.1.0 for Puppet 5
- Remove old puppet tests that won't work with Hiera 5,
as systemd 2.1.0 uses Hiera 5
SIMP-5289 #comment update rsyslog's systemd dependency
> (SIMP-5289) Update to camptocamp/systemd 2.1.0 for Puppet 5

- .fixtures.yml
- CHANGELOG
- metadata.json
Revert back to simp/systemd and expand version range allowed.
We cannot change back from simp/systemd to camptocamp/systemd
because of flaws in simp-adapter WRT RPM upgrades. We do want
to advance to version 2.1.0, but will have to pull that version
forward into our simp/systemd version. The simp-adapter problem
will be resolved when we rework packaging of modules in RPMs
(6.4.0 or later).
> (SIMP-5289) Revert back to simp/systemd

- CHANGELOG
- manifests/config.pp
- spec/classes/init_spec.rb
- spec/fixtures/hieradata/rsyslog_config_settings
- spec/fixtures/hieradata/rsyslog_config_settings.yaml
- templates/config/pre_logging.conf.erb
- templates/sysconfig.erb
- Added logic to properly handle rsyslogd parameters for V8.6 and later
as documented in CentOS 7.5 Release notes.  These include moving -x
and -w options from parameters to entries in global.conf and issuing
deprecation warning for -l and -s options.
SIMP-5315 #close
SIMP-5405 #close
SIMP-5406 #close
SIMP-5407 #close
> (SIMP-5315) Updated rsyslogd parameters

- CHANGELOG
This bad entry causes a significant part of the CHANGELOG for 7.3.0 to be missing.
> (SIMP-MAINT) Fix bad changelog entry

- spec/acceptance/suites/default/00_default_spec.rb
- spec/acceptance/suites/default/01_client_server_no_tls_spec.rb
- spec/acceptance/suites/doubleforward/01_client_tls_server_no_tls_nextserver_spec.rb
- spec/acceptance/suites/failover/04_failover_no_tls_spec.rb
Fixed all suites by compiling manifests twice before checking
for idempotency.  To verify the fixes, run each suite with its
corresponding centos-6 node set.
SIMP-5709 #close
> (SIMP-5709) rsyslog acceptance tests fail on CentOS 6

- CHANGELOG
- manifests/rule/local.pp
- metadata.json
- spec/defines/rule/local_spec.rb
- types/queuetype.pp
- Set rsyslog::rule::local::file_create_mode to 0640 by default
- Allow the following to be set directly via Hiera using simplib::dlookup:
- rsyslog::rule::local::file_create_mode
- rsyslog::rule::local::dir_create_mode
- rsyslog::rule::local::queue_max_file_size
SIMP-6244 #close
> (SIMP-6244) Update file_create_mode for local rule

- CHANGELOG
- manifests/config.pp
- metadata.json
- spec/classes/init_spec.rb
- spec/fixtures/hieradata/include_rsyslog_d.yaml
The $IncludeConfig for rsyslog.d should end in *.conf to ensure that
only valid config files are read and not other files that may exist in
that directory
SIMP-7177 #close
> [SIMP-7177] fix broken include for rsyslog.d

- .gitlab-ci.yml
- .travis.yml
- Gemfile
This patch updates the puppet and ruby versions in the Gitlab CI
pipeline to reflect the latest PE LTS releases.  Most notably, it adds
specific tests for PE2019.8 LTS.
SIMP-7909 #close
[SIMP-7848] #comment Add PE2019.8 to GL CI in pupmod-simp-rsyslog
[SIMP-7855] #comment Update GL CI to PE2018.1.15 in pupmod-simp-rsyslog
[SIMP-7848]: https://simp-project.atlassian.net/browse/SIMP-7848
[SIMP-7855]: https://simp-project.atlassian.net/browse/SIMP-7855
> (SIMP-7848) Add PE2019.8 to pupmod-simp-rsyslog GL pipeline

- CHANGELOG
- metadata.json
Manually fix problem that used to be detected automatically by
pkg:compare_latest_tag rake task.
SIMP-8344 #close
> (SIMP-8344) rsyslog has unreleased doc updates

- .github/workflows/pr_glci.yml
- .github/workflows/pr_glci_manual.yml
- .github/workflows/pr_tests.yml
- .gitlab-ci.yml
This patch updates the standardized GitHub Actions that trigger GLCI
pipelines:
- Still preemptively cancels existing GLCI pipelines for the same
branch, EXCEPT when a pipeline is for the same commit hashref.
- Refactored common GLCI logic into new composite run steps actions:
- [github-action-gitlab-ci-pipeline-trigger@v1][0]
- [github-action-gitlab-ci-syntax-check@v1][1]
This patch also enforces the standardized asset baseline using
simp/puppetsync, and may apply other updates to ensure conformity.
CI: SKIP MATRIX
[SIMP-9329] #close
[SIMP-9266] #comment Standardized GHA + assets in pupmod-simp-rsyslog
[SIMP-9279] #comment `.fixtures.yml` triggers GLCI acc for pupmod-simp-rsyslog
[0]: https://github.com/simp/github-action-gitlab-ci-pipeline-trigger
[1]: …
> (SIMP-9266) Improve GHA GCLI trigger in pupmod-simp-rsyslog

- lib/facter/rsyslogd.rb
- spec/spec_helper.rb
- spec/unit/facter/rsyslogd_spec.rb
Fixed a bug where the rsyslogd fact transformed all rsyslogd features
reported by 'rsyslogd -v' into boolean values, even though some
features should have been left as strings.
The logic flaws resulted in a warning message when the fact was loaded
in some versions of Puppet 7.
SIMP-9235 #close
> (SIMP-9235) rsyslogd fact transforms string features to boolean

- .fixtures.yml
- .gitlab-ci.yml
- spec/acceptance/nodesets/centos-7.yml
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/oel.yml
- spec/acceptance/suites/doubleforward/nodesets/centos-7.yml
- spec/acceptance/suites/doubleforward/nodesets/default.yml
- spec/acceptance/suites/doubleforward/nodesets/oel.yml
- spec/spec_helper_acceptance.rb
* Add a Puppet 7 acceptance test
* Remove check for Puppet >=6 in .fixtures.yml
* Test with CentOS 8.4 via generic/centos8 box
* Fail acceptance tests if no examples are executed.
[SIMP-9666] #comment pupmod-simp-rsyslog acceptance tests configured
SIMP-10057 #close
[SIMP-9666]: https://simp-project.atlassian.net/browse/SIMP-9666
> (SIMP-10057) rsyslog Add Puppet 7 acceptance test

- .fixtures.yml
- .gitignore
- CHANGELOG
- manifests/config.pp
- metadata.json
- spec/acceptance/nodesets/centos-7.yml
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/oel.yml
- spec/acceptance/suites/doubleforward/nodesets/centos-7.yml
- spec/acceptance/suites/doubleforward/nodesets/default.yml
- spec/acceptance/suites/doubleforward/nodesets/oel.yml
- spec/classes/init_spec.rb
This patch updates from camptocamp/systemd 2.x to puppet/systemd 3.x
This bump is driven by simp/simp-core#829
> Update deps to use puppet/systemd

- .github/workflows/pr_tests.yml
- .gitlab-ci.yml
- Gemfile
- spec/acceptance/nodesets/oel.yml
- spec/acceptance/suites/doubleforward/nodesets/oel.yml
This patch moves puppet 6 refs to 7, puppet 7 refs to 8. Then we manually
update all spec nodesets to point to sicura oel boxes and comment out all 
pup8 tests.
The patch enforces a standardized asset baseline using simp/puppetsync,
and may also apply other updates to ensure conformity.
> Removes puppet 6 from .gitlab-ci.yml

- .github/workflows/pr_tests.yml
- .puppet-lint.rc
- CHANGELOG
- Gemfile
- manifests/config.pp
- manifests/install.pp
- manifests/rule/remote.pp
- manifests/server.pp
- manifests/server/selinux.pp
- metadata.json
- spec/classes/server_spec.rb
This patch adds support for RockyLinux 8
The patch enforces a standardized asset baseline using simp/puppetsync,
and may also apply other updates to ensure conformity.
> Add RockyLinux 8 support
