simp/pupmod-simp-rsyslog

- README.md
- manifests/server/selinux.pp
- templates/pre_logging.conf.erb
Minor updates found during final testing.
README updates.
SIMP-58 #close #Test updates and bug fix
Change-Id: I8d295ef4f128adb0a7b3d4449a1e1048115a5473
> (SIMP-58) Test updates and bug fix

- manifests/server.pp
- spec/acceptance/client_server_udp_spec.rb
- spec/helpers.rb
- spec/spec_helper_acceptance.rb
- templates/pre_logging.conf.erb
Fixes the UDP rsyslog code and adds acceptance tests for a single server
and client.
SIMP-425 #close UDP Acceptance tests pass
Change-Id: I2c5dfaffe9ae14a169657473311b9399c9173880
> (SIMP-425) Test UDP Rsyslog

- spec/helpers.rb
> Left pry in place

- .fixtures.yml
- build/pupmod-rsyslog.spec
- manifests/config.pp
- manifests/init.pp
- manifests/server.pp
- metadata.json
Enables compliance checking support for rsyslog module
SIMP-720 #comment added compliance support
> (SIMP-720) Map 800-53 requirements to hiera

- build/pupmod-rsyslog.spec
- manifests/init.pp
- metadata.json
- Migrated use_simp_pki to a global catalyst.
SIMP-894 #comment Fixes for issues discovered during testing
> (SIMP-894) Fixed issues discovered during testing

- CHANGELOG
- build/rpm_metadata/requires
- metadata.json
> (SIMP-2019) Update iptables dep version

- README.md
Created a more usage-based RSyslog README.md format.
> (SIMP-1861) Simplify Rsyslog README

- CHANGELOG
- manifests/rule/drop.pp
> (SIMP-2529) Added trailing newline to drop rules

- .travis.yml
- CHANGELOG
- manifests/config/logrotate.pp
- metadata.json
- update path to systemctl
SIMP-2887  #comment updated rsyslog
SIMP-2889  #close
> (SIMP-2887) update path to systemctl

- CHANGELOG
- manifests/server.pp
- metadata.json
- spec/classes/server_spec.rb
- selinux_enabled default now uses str2bool for robustness
SIMP-3013 #close
> (SIMP-3013) Updated server defaults

- .fixtures.yml
- CHANGELOG
- Gemfile
- manifests/config/logrotate.pp
- spec/classes/init_spec.rb
SIMP-2045 #rsyslog done
SIMP-3042 #close
> (SIMP-2045) Updated logrotate::rule to use new lastaction API

- .gitlab-ci.yml
> (SIMP-3158) add gitlabci to simp module

- .fixtures.yml
- .gitlab-ci.yml
- .travis.yml
SIMP-3903 #comment rsyslog use concat 4.1.1 in tests
> (SIMP-3903) rsyslog use concat 4.1.1 in tests

- .fixtures.yml
- .gitlab-ci.yml
- CHANGELOG
- manifests/install.pp
- metadata.json
- spec/acceptance/nodesets/centos-6.yml
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/oel.yml
- spec/acceptance/suites/default/00_default_spec.rb
- spec/acceptance/suites/default/02_client_server_udp_spec.rb
- spec/acceptance/suites/doubleforward/01_client_tls_server_no_tls_nextserver_spec.rb
- spec/acceptance/suites/failover/04_failover_no_tls_spec.rb
- spec/acceptance/suites/failover/05_failover_using_tls_spec.rb
- spec/classes/init_spec.rb
SIMP-2971 #comment update rsyslog
> (SIMP-2971) Add $package_ensure

- CHANGELOG
- manifests/config.pp
- spec/classes/init_spec.rb
> (SIMP-5497) Fixed a bug in the systemd override

- .fixtures.yml
- CHANGELOG
- metadata.json
https://gitlab.com/simp/pupmod-simp-rsyslog/pipelines/53767715
> (SIMP-6263) Revert to using camptocamp/systemd

- .gitlab-ci.yml
- Add back in missing suites
- Add back in missing centos-6 nodeset
SIMP-6999 #close
> (SIMP-6999) Only default suite run in GitLab

- CHANGELOG
- manifests/rule/local.pp
- metadata.json
- spec/defines/rule/local_spec.rb
- templates/rule/local.erb
- Update local rule defined type to use the same package defaults for
queues as the remote rule defined type
- Update local rule template to check for optional parameters
- Update spec tests to properly reflect these new defaults
SIMP-7779 #close
> (SIMP-7779) Standardize local rule queue defaults

- CHANGELOG
- metadata.json
- spec/classes/expected/global_default.txt
- spec/classes/expected/global_extra_globals.txt
- spec/classes/expected/global_extra_main_queue_params.txt
- spec/classes/expected/global_extra_misc_input_module_params.txt
- spec/classes/expected/global_extra_tcp_server_input_module_params.txt
- spec/classes/expected/global_extra_tls_tcp_server_input_module_params.txt
- spec/classes/expected/global_extra_udp_server_input_module_params.txt
- spec/classes/expected/global_tcp_server.txt
- spec/classes/expected/global_tls_logging.txt
- spec/classes/expected/global_tls_tcp_server.txt
- spec/classes/expected/global_udp_server.txt
- templates/config/pre_logging.conf.erb
> (#150) Changed legacy control character params into global params

- .github/workflows/pr_tests.yml
- .rubocop.yml
- CHANGELOG
- Gemfile
- lib/facter/rsyslogd.rb
- metadata.json
- spec/acceptance/suites/compliance/00_simp_profile_install_spec.rb
- spec/acceptance/suites/compliance/01_simp_profile_inspec_spec.rb
- spec/acceptance/suites/default/00_default_spec.rb
- spec/acceptance/suites/default/01_client_server_no_tls_spec.rb
- spec/acceptance/suites/default/02_client_server_udp_spec.rb
- spec/acceptance/suites/default/03_client_server_using_tls_spec.rb
- spec/acceptance/suites/doubleforward/01_client_tls_server_no_tls_nextserver_spec.rb
- spec/acceptance/suites/failover/04_failover_no_tls_spec.rb
- spec/acceptance/suites/failover/05_failover_using_tls_spec.rb
- spec/classes/init_spec.rb
- spec/classes/server_spec.rb
- spec/defines/rule/console_spec.rb
- spec/defines/rule/data_source_spec.rb
- spec/defines/rule/drop_spec.rb
- spec/defines/rule/local_spec.rb
- spec/defines/rule/other_spec.rb
- spec/defines/rule/remote_spec.rb
- spec/defines/rule_spec.rb
- spec/spec_helper.rb
- spec/spec_helper_acceptance.rb
- spec/unit/compliance_engine/compliance_engine_enforce_spec.rb
- spec/unit/facter/rsyslogd_spec.rb
- templates/config/pre_logging.conf.erb
Also fix use of legacy facts
Closes #157
> Clean up for rubocop
